---
# - name: Check OS version and family
#   ansible.builtin.assert:
#     that:
#       - ansible_os_family == 'Windows'
#       - ansible_distribution | regex_search('(Microsoft Windows Server 2019)')
#     success_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is the detected operating system."
#     fail_msg: "This role can only be run against Windows Server 2019 Editions. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
#   tags:
#     - always

# - name: Include the preliminary tasks
#   ansible.builtin.include_tasks: prelim.yml
#   tags:
#     - always
#     - prelim_tasks

- name: Execute the section 1 tasks
  hosts: all
  vars_files:
    - ../vars/main.yml
  tasks:
    - import_tasks: section1.yml
      when: win19cis_section01
  tags:
    - section01
# - name: Execute the section 2 tasks
#   ansible.builtin.import_tasks: section2.yml
#   when: win19cis_section02
#   tags:
#     - section02

# - name: If Warnings found Output count and control IDs affected
#   ansible.builtin.debug:
#     msg:
#       - "You have {{ warn_count }} Warning(s) that require investigation(s). Their ID’s are listed below:"
#       - "{{ warn_control_list }}"
#   when: warn_count != 0
