name: build-image

on: workflow_dispatch

jobs:
  build-push:
    if: ${{ github.actor == vars.MY_NAME }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: "{{defaultContext}}:/"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Delete package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: "Automate-Server-Hardening"
          package-type: "container"
          min-versions-to-keep: 2
          delete-only-untagged-versions: "true"
