name: Clear all Github actions caches

on: workflow_dispatch
env:
  env_var: ${{ vars.ADMIN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clear caches
        run: |
          echo $ADMIN_NAME
  # clear-caches:
  #   name: Delete all caches
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: write
  #   steps:
  #     - name: Clear caches
  #       uses: easimon/wipe-cache@main
  #       with:
  #         dry-run: "false"
