name: Clear all Github actions caches

on: workflow_dispatch

jobs:
  clear-caches:
    if: ${{ github.actor == 'Ziim-eiei' }}
    name: Delete all caches
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main
        with:
          dry-run: "false"
