name: Clear all Github actions caches

on: workflow_dispatch

jobs:
  clear-caches:
    name: Delete all caches
    runs-on: ubuntu-20.04
    permissions:
      actions: write
    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@main
        with:
          dry-run: "true"
