name: delete-package
on: workflow_call
jobs:
  delete-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: "Automate-Server-Hardening"
          package-type: "container"
          min-versions-to-keep: 1
          delete-only-untagged-versions: "true"
