name: delete-package
on: workflow_dispatch
jobs:
  delete-package:
    runs-on: ubuntu-latest
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@v5.0.0
        with:
          token: ${{ secrets.MY_PAT }}
          package-name: "Automate-Server-Hardening"
          package-type: "container"
          min-versions-to-keep: 1
          delete-only-untagged-versions: "true"
